---
title: "Analysis"
output: html_document
---
```{r}
# load necessary libraries
  library(stringr)
  library(car)
```

```{r}
  # The url for the NOAA Juneau airport weather data CSV file
  csv_url <- "https://www.ncei.noaa.gov/access/past-weather/USW00025309/data.csv"
  
  # import the Juneau dataset
  Juneau <- read.csv(csv_url, skip = 1)
  head(Juneau)

  # subset data to just 2023 by filtering the data column to strings with just "2023" as the first four characters
  data_2023 <- Juneau[substr(Juneau$Date, 1, 4) == "2023", ]
  head(data_2023)
```
  
```{r}
  # histogram of average temp in 2023
  hist(data_2023$TAVG..Degrees.Fahrenheit., 
       main = "Histogram of Average Temperatures in Juneau (2023)", 
       xlab = "Average Temperature (°F)", 
       ylab = "Frequency", 
       col = "blue", 
       border = "black")
  
  # histogram of average temp by month in 2023
  data_2023$Month <- as.numeric(substr(data_2023$Date, 6, 7))
  par(mfrow = c(3, 4)) # set up a 3
  for (month in 1:12) {
    hist(data_2023$TAVG..Degrees.Fahrenheit.[data_2023$Month == month], 
         main = paste("Histogram of Avg Temp - Month", month, "(2023)"), 
         xlab = "Average Temperature (°F)", 
         ylab = "Frequency", 
         col = "lightblue", 
         border = "black")
  }
```

```{r}
  # Investigation of average temp by seasons for 2023
  season_data <- data_2023
  
  fall_months <- c(9, 10, 11)
  winter_months <- c(12, 1, 2)
  spring_months <- c(3, 4, 5)
  summer_months <- c(6, 7, 8)
  
  fall_avg <- season_data$TAVG..Degrees.Fahrenheit.[season_data$Month %in% fall_months]
  winter_avg <- season_data$TAVG..Degrees.Fahrenheit.[season_data$Month %in% winter_months]
  spring_avg <- season_data$TAVG..Degrees.Fahrenheit.[season_data$Month %in% spring_months]
  summer_avg <- season_data$TAVG..Degrees.Fahrenheit.[season_data$Month %in% summer_months]
  
  seasonal_averages <- list(Fall = fall_avg, Winter = winter_avg, Spring = spring_avg, Summer = summer_avg)
  
  # plot a histogram of each seasons average temps. Include the standard deviation of the average temps for that season in a legend.
  par(mfrow = c(2, 2)) # set up a 2x2 plot layout
  for (season in names(seasonal_averages)) {
    avg_temps <- seasonal_averages[[season]]
    hist(avg_temps, 
         main = paste("Histogram of Avg Temp -", season, "(2023)"), 
         xlab = "Average Temperature (°F)", 
         ylab = "Frequency", 
         col = "lightcoral", 
         border = "black")
    sd_temp <- sd(avg_temps, na.rm = TRUE)
    legend("topright", legend = paste("SD:", round(sd_temp, 2)), bty = "n")
  }
```
```{r}
  # using a levene's test to see if there is a significant difference in variance between the seasons.
  # randomly sample 45 data points from each season to ensure equal sample sizes

  set.seed(42) # for reproducibility
  sample_size <- 45

  fall_sample <- sample(fall_avg, sample_size, replace = TRUE)
  winter_sample <- sample(winter_avg, sample_size, replace = TRUE)
  spring_sample <- sample(spring_avg, sample_size, replace = TRUE)
  summer_sample <- sample(summer_avg, sample_size, replace = TRUE)
  seasonal_samples <- data.frame(
    Temp = c(fall_sample, winter_sample, spring_sample, summer_sample),
    Season = factor(rep(c("Fall", "Winter", "Spring", "Summer"), each = sample_size))
  )
  
  # run the levene's test pairwise between the seasons
  levene_fall_winter <- leveneTest(Temp ~ Season, data = seasonal_samples[seasonal_samples$Season %in% c("Fall", "Winter"), ])
  print(levene_fall_winter)
  levene_winter_spring <- leveneTest(Temp ~ Season, data = seasonal_samples[seasonal_samples$Season %in% c("Winter", "Spring"), ])
  print(levene_winter_spring)
  levene_fall_summer <- leveneTest(Temp ~ Season, data = seasonal_samples[seasonal_samples$Season %in% c("Fall", "Summer"), ])
  print(levene_fall_summer)
  levene_spring_summer <- leveneTest(Temp ~ Season, data = seasonal_samples[seasonal_samples$Season %in% c("Spring", "Summer"), ])
  print(levene_spring_summer)
  
  
  levene_fall_spring <- leveneTest(Temp ~ Season, data = seasonal_samples[seasonal_samples$Season %in% c("Fall", "Spring"), ])
  print(levene_fall_spring)
  levene_winter_summer <- leveneTest(Temp ~ Season, data = seasonal_samples[seasonal_samples$Season %in% c("Winter", "Summer"), ])
  print(levene_winter_summer)
  
```

```{r}
  # histogram of average temp by year for years 2010 to 2023
  Juneau$Year <- as.numeric(substr(Juneau$Date, 1, 4))
  par(mfrow = c(6, 4)) # set up a 6
  for (year in 2014:2023) {
    # graph and make sure the x axis is consistent across all histograms
    hist(Juneau$TAVG..Degrees.Fahrenheit.[Juneau$Year == year], 
         main = paste("Histogram of Avg Temp - Year", year), 
         xlab = "Average Temperature (°F)", 
         ylab = "Frequency", 
         col = "lightgreen", 
         border = "black", 
         xlim = c(min(Juneau$TAVG..Degrees.Fahrenheit., na.rm = TRUE), max(Juneau$TAVG..Degrees.Fahrenheit., na.rm = TRUE)))
  }
```


```{r}
# investigate the relationship between TAVG and Percipitation,Snow, and SnowDepth
  Tavg <- data_2023$TAVG..Degrees.Fahrenheit.
  percipitation <- data_2023$PRCP..Inches.
  Snow <- data_2023$SNOW..Inches.
  SnowDepth <- data_2023$SNWD..Inches.
  
  plot(percipitation, Tavg, 
       main = "Average Temperature vs. Precipitation (2023)", 
       xlab = "Precipitation (inches)", 
       ylab = "Average Temperature (°F)", 
       col = "red", 
       pch = 19)
  plot(Snow, Tavg,
       main = "Average Temperature vs. Snow (2023)", 
       xlab = "Precipitation (inches)", 
       ylab = "Average Temperature (°F)", 
       col = "red", 
       pch = 19)
  plot(SnowDepth, Tavg,
       main = "Average Temperature vs. Snow Depth (2023)",
       xlab = "Snow Depth (inches)",
       ylab = "Average Temperature (°F)",
       col = "red",
       pch = 19)
```
```{r}
  # bin the TAVG by 10 degree increments
  bins <- cut(Tavg, breaks = seq(floor(min(Tavg, na.rm = TRUE)/10)*10, ceiling(max(Tavg, na.rm = TRUE)/10)*10, by = 10), include.lowest = TRUE)
  binned_data <- data.frame(Tavg = Tavg, Percipitation = percipitation, Snow = Snow, SnowDepth = SnowDepth, Bin = bins)
  
  # remove rows with zero percip, snow, or snowdepth to avoid skewing the analysis.
  binned_data <- binned_data[binned_data$Percipitation > 0 & binned_data$Snow > 0 & binned_data$SnowDepth > 0, ]
  
  # plot new tavg vs percipitation, snow, and snowdepth
  plot(binned_data$Percipitation, binned_data$Tavg,
       main = "Binned Average Temperature vs. Precipitation (2023)", 
       xlab = "Precipitation (inches)", 
       ylab = "Average Temperature (°F)", 
       col = "green", 
       pch = 19)
  plot(binned_data$Snow, binned_data$Tavg,
       main = "Binned Average Temperature vs. Snow (2023)",
       xlab = "Snow (inches)",
       ylab = "Average Temperature (°F)",
       col = "green",
       pch = 19)
  plot(binned_data$SnowDepth, binned_data$Tavg,
       main = "Binned Average Temperature vs. Snow Depth (2023)",
       xlab = "Snow Depth (inches)",
       ylab = "Average Temperature (°F)",
       col = "green",
       pch = 19)

  mod <- lm(Percipitation ~ Bin, data = binned_data)
  # residuals plot
  plot(mod$residuals, 
       main = "Residuals of Percipitation Model", 
       ylab = "Residuals", 
       xlab = "Index", 
       col = "purple", 
       pch = 19)
  summary(mod)
  
  mod2 <- lm(Snow ~ Bin, data = binned_data)
  # residuals plot
  plot(mod2$residuals, 
       main = "Residuals of Percipitation Model", 
       ylab = "Residuals", 
       xlab = "Index", 
       col = "purple", 
       pch = 19)
  summary(mod2)
  
  mod3 <- lm(SnowDepth ~ Bin, data = binned_data)
  # residuals plot
  plot(mod3$residuals, 
       main = "Residuals of Percipitation Model", 
       ylab = "Residuals", 
       xlab = "Index", 
       col = "purple", 
       pch = 19)
  summary(mod3)

```
  
  
  
  
  
  
  